apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "certificate-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "certificate-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "certificate-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "certificate-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
