apiVersion: v1
kind: Service
metadata:
  name: {{ include "certificate-operator.fullname" . }}-metrics-service
  labels:
    {{- include "certificate-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.ports.https.name }}
    port: {{ .Values.service.ports.https.port }}
    protocol: {{ .Values.service.ports.https.protocol }}
    targetPort: {{ .Values.service.ports.https.targetPort }}
  selector:
    control-plane: controller-manager
