apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificateConfig.secret.name }}
  namespace: {{ .Values.certificateConfig.secret.namespace }}
  labels:
    {{- include "certificate-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |
    {
      "apiEndpoint": {{ .Values.certificateConfig.secret.credentials.apiEndpoint | quote }},
      "token": {{ .Values.certificateConfig.secret.credentials.token | quote }},
      "downloadEndpoint": {{ .Values.certificateConfig.secret.credentials.downloadEndpoint | quote }}
    }
